export const ACTION_EAST = 'DIRECTION_ACTION_EAST';
export const ACTION_WEST = 'DIRECTION_ACTION_WEST';
export const ACTION_SOUTH = 'DIRECTION_ACTION_SOUTH';
export const ACTION_NORTH = 'DIRECTION_ACTION_NORTH';
export const ACTION_SOUTH_EAST = 'DIRECTION_ACTION_SOUTH_EAST';
export const ACTION_SOUTH_WEST = 'DIRECTION_ACTION_SOUTH_WEST';
export const ACTION_NORTH_EAST = 'DIRECTION_ACTION_NORTH_EAST';
export const ACTION_NORTH_WEST = 'DIRECTION_ACTION_NORTH_WEST';

